[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_APP_EMAILJS_SERVICE_ID,VITE_APP_EMAILJS_TEMPLATE_ID,VITE_APP_EMAILJS_PUBLIC_KEY"